<?php
/**
 * See LICENSE.md for license details.
 */
?>

<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dhl\PaketReturns\ViewModel\Sales\Rma\Form $viewModel */
$viewModel = $block->getData('viewModel');
$shipments = $viewModel->getShipments();
$address = $viewModel->getAddress();
$recipientStreet = $viewModel->getRecipientStreet();
?>

<?php if (!empty($shipments) && !empty($address)): ?>
<form id="form-dhlpaket-rma"
      method="post"
      action="<?= $block->escapeUrl($viewModel->getSubmitUrl()) ?>"
      enctype="multipart/form-data"
      class="form-returns-create form-address-edit"
>
    <fieldset class="fieldset">
        <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend>

        <div class="field field-name-firstname required">
            <label class="label" for="firstname"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
            <div class="control">
                <input type="text" name="address[firstname]" id="firstname" class="input-text required-entry"
                       value="<?= $block->escapeHtmlAttr($address->getFirstname()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('First Name')) ?>">
            </div>
        </div>

        <div class="field field-name-lastname required">
            <label class="label" for="lastname"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
            <div class="control">
                <input type="text" name="address[lastname]" id="lastname" class="input-text required-entry"
                       value="<?= $block->escapeHtmlAttr($address->getLastname()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>">
            </div>
        </div>

        <div class="field company">
            <label for="company" class="label"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input type="text" name="address[company]" id="company" class="input-text"
                       value="<?= $block->escapeHtmlAttr($address->getCompany()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Company')) ?>">
            </div>
        </div>

        <div class="field email">
            <label for="email" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="text" name="address[email]" id="email" class="input-text"
                       value="<?= $block->escapeHtmlAttr($address->getEmail()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>">
            </div>
        </div>

        <div class="field telephone">
            <label for="telephone" class="label"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text" name="address[telephone]" id="telephone" class="input-text"
                       value="<?= $block->escapeHtmlAttr($address->getTelephone()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>">
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>

        <div class="field street required">
            <label for="street_name" class="label"><span><?= $block->escapeHtml(__('Street Name')) ?></span></label>
            <div class="control">
                <input type="text" name="address[street_name]"
                       id="street_name" class="input-text required-entry"
                       value="<?= $block->escapeHtmlAttr($recipientStreet->getName()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Street Name')) ?>">
            </div>
        </div>

        <div class="field required">
            <label for="street_number" class="label"><span><?= $block->escapeHtml(__('Street Number')) ?></span></label>
            <div class="control">
                <input type="text" name="address[street_number]"
                       id="street_number" class="input-text required-entry"
                       value="<?= $block->escapeHtmlAttr($recipientStreet->getNumber()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Street Number')) ?>">
            </div>
        </div>

        <div class="field city required">
            <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input type="text" name="address[city]" id="city" class="input-text required-entry"
                       value="<?= $block->escapeHtmlAttr($address->getCity()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>">
            </div>
        </div>

        <div class="field region required">
            <label class="label" for="region_id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
            <div class="control">
                <select name="address[region_id]" id="region_id" class="validate-select region_id"
                        title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>">
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" name="address[region]" id="region" class="input-text validate-not-number-first"
                       value="<?= $block->escapeHtmlAttr($address->getRegion()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>">
            </div>
        </div>

        <div class="field zip required">
            <label class="label" for="zip"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="control">
                <input type="text" name="address[postcode]" id="zip" class="input-text validate-zip-international required-entry"
                       value="<?= $block->escapeHtmlAttr($address->getPostcode()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>">
                <div role="alert" class="message warning" style="display:none">
                    <span></span>
                </div>
            </div>
        </div>

        <div class="field country required">
            <label class="label" for="country"><span><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= /* @noEscape */ $viewModel->getCountrySelectHtml($address->getCountryId(), 'address[country]') ?>
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Return Items Information')) ?></span></legend>
        <?php foreach ($shipments as $shipment): ?>
        <table>
            <caption><?= $block->escapeHtml(__('Shipment # %1', $shipment->getIncrementId())) ?></caption>
            <colgroup>
                <col class="col-ret-item">
                <col class="col-ret-sku">
                <col class="col-ret-qty">
            </colgroup>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Item')) ?></span></th>
                    <th class="col sku" scope="col"><span><?= $block->escapeHtml(__('SKU')) ?></span></th>
                    <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                </tr>
            </thead>
            <?php /** @var \Magento\Sales\Model\Order\Shipment\Item $item */ ?>
            <?php foreach ($shipment->getAllItems() as $item): ?>
            <?php if (!$item->getOrderItem()->getParentItem()): ?>
                <?= /* @noEscape */ $viewModel->getItemDetailsHtml($item) ?>
            <?php endif; ?>
            <?php endforeach; ?>
        </table>
        <?php endforeach; ?>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" id="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>"><span><?= $block->escapeHtml(__('Submit')) ?></span></button>
        </div>
    </div>
</form>
<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){
        var dataForm = $('#form-dhlpaket-rma');
        dataForm.mage('validation');
    });
</script>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": true,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-dhlpaket-rma",
                "regionJson": <?= /* @noEscape */ $viewModel->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ (int) $address->getRegionId() ?>",
                "currentRegion": "<?= /* @noEscape */ (int) $address->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $viewModel->getCountriesWithOptionalZipJson() ?>
            }
        }
    }
</script>

<?php endif; ?>
