<?php
/**
 * See LICENSE.md for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Dhl\PaketReturns\ViewModel\Sales\Order\Info\Button\Returns $viewModel */
$viewModel = $block->getData('viewModel');
$url = $viewModel->getReturnCreateUrl();
?>
<?php if ($url): ?>
    <a href="<?= $block->escapeUrl($url) ?>" class="action return"><span><?= $block->escapeHtml(__('Create Return Label')) ?></span></a>
<?php endif; ?>
